"""empty message

Revision ID: 3844e0d43a59
Revises: 6ba92c036b86
Create Date: 2017-01-05 01:34:28.814447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3844e0d43a59'
down_revision = '6ba92c036b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notes', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
